name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Ubuntu / ${{ matrix.node-ver }}
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    strategy:
      matrix:
        node-ver: [16.x, 18.x, 20.x, latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NodeJS / ${{ matrix.node-ver }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-ver }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Lint the project
      run: npm run ci-lint
    - name: Clean the project
      run: rm --recursive cache --verbose
